# LoadBalancer (using NGINX as an example)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadbalancer
  template:
    metadata:
      labels:
        app: loadbalancer
    spec:
      containers:
      - name: loadbalancer
        image: nginx:latest