# VPN (using OpenVPN as an example)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn
  template:
    metadata:
      labels:
        app: vpn
    spec:
      containers:
      - name: vpn
        image: openvpn:latest